### ISSUE TITLE
KNOWLEDGE TRANSFER & HAND OVER TASK

### ISSUE THREAD

**Issue by DHANDAPANISATTANATHAN** [SSOMENSREPO/EI-PHP-GAE#10]
<h3>KT TO SL<h3>
**TASK OWNER: SKL , RAJA & SL**

SKL & RAJA - YOU BOTH HAND OVER ALL YOUR EI PHP FORMS TO SL IMMEDIATELY.

AND PUSH IN GIT HUB WAT EVER YOU DID UPTO NOW.

* Status : **New**

**Comment by DHANDAPANISATTANATHAN** [comment]
SKL , RAJA & SL

Update this task staus immediately!!!!!!

*Status:**to_be_Clarify**

**Comment by SasikalaDjeasankar** [comment]
Forms which i Did in EI.
   1.Expense
      I) Biz Expense Both daily and Detail
      II)Personal Expense
      III) Staff Daily Corrections which was done LL.
   2.Customer
     I)Customer Termination.

For all forms I completed and uploaded the latest script in Github, for staff Daily, expense type staff need to do update and delete part and some radio button validation.

For customer termination need to implement error message getting from sp and show in message box. this one need to do after sql team finish.

* status: **Done**

**Comment by Rajagunasekaran** [comment]
All UNIT, ACCESS CARD, REPORT CHARTS AND DD forms are finished, except DD extraction pdf mail part. All are updated in Git Hub.

* status **Done**

**Comment by SaradambalMunusamy** [comment]
HERE AFTER I LL TAKE FORM COPY FROM GITHUB IF ANY ISSUES OR CR

STATUS:DONE

**Comment by DHANDAPANISATTANATHAN** [comment]
<h4>KT TO SKL</h4>

TASK OWNER: RAJA

KT all your EI AND LMC forms to SKL

* Status : **New**

**Comment by Rajagunasekaran** [comment]
All EI-PHP and LMC Forms KT'ed to SKL

* status:**DONE**

**Comment by SasikalaDjeasankar** [comment]
I got KT from Raja for both EI & LMC  and also updated in Sheets. Hereafter I'll take care of his forms.


* status : **Closed**
