### ISSUE TITLE
ISSUE IN PHP ON 26/06/2015

### ISSUE THREAD

**Issue by DHANDAPANISATTANATHAN** [SSOMENSREPO/EI-PHP-GAE#13]
DEFECT OWNER: EI PHP TEAM

![issue_25062015](https://cloud.githubusercontent.com/assets/9882142/8371269/c2da8574-1bf2-11e5-826d-bdad78922932.png)

**Comment by SaradambalMunusamy** [comment]
As per above issue cleared amount as per point 3 and then as per 5th one cleared issues in php
